const mockUser = {
  login: "faychan",
  id: 21170457,
  node_id: "MDQ6VXNlcjIxMTcwNDU3",
  avatar_url: "https://avatars.githubusercontent.com/u/21170457?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/faychan",
  html_url: "https://github.com/faychan",
  followers_url: "https://api.github.com/users/faychan/followers",
	following_url: "https://api.github.com/users/faychan/following{/other_user}",
  gists_url: "https://api.github.com/users/faychan/gists{/gist_id}",
  starred_url: "https://api.github.com/users/faychan/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/faychan/subscriptions",
  organizations_url: "https://api.github.com/users/faychan/orgs",
  repos_url: "https://api.github.com/users/faychan/repos",
  events_url: "https://api.github.com/users/faychan/events{/privacy}",
  received_events_url: "https://api.github.com/users/faychan/received_events",
  type: "User",
  site_admin: false,
  name: "Farah Noriffat",
  company: "Panggilin",
  blog: "fay-portfolio.com",
  location: "INA",
  email: null,
  hireable: null,
  bio: "A sophisticated individual who ventures into the world of coding then falls in love with it.",
  twitter_username: null,
  public_repos: 65,
  public_gists: 0,
  followers: 4,
  following: 3,
  created_at: "2016-08-22T08:56:50Z",
  updated_at: "2022-07-18T13:29:03Z"
}
export default mockUser;