const mockFollowers = [
  {
    "login": "yoesuv",
    "id": 7220115,
    "node_id": "MDQ6VXNlcjcyMjAxMTU=",
    "avatar_url": "https://avatars.githubusercontent.com/u/7220115?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/yoesuv",
    "html_url": "https://github.com/yoesuv",
    "followers_url": "https://api.github.com/users/yoesuv/followers",
    "following_url": "https://api.github.com/users/yoesuv/following{/other_user}",
    "gists_url": "https://api.github.com/users/yoesuv/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/yoesuv/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/yoesuv/subscriptions",
    "organizations_url": "https://api.github.com/users/yoesuv/orgs",
    "repos_url": "https://api.github.com/users/yoesuv/repos",
    "events_url": "https://api.github.com/users/yoesuv/events{/privacy}",
    "received_events_url": "https://api.github.com/users/yoesuv/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "FahedHermoza",
    "id": 8326973,
    "node_id": "MDQ6VXNlcjgzMjY5NzM=",
    "avatar_url": "https://avatars.githubusercontent.com/u/8326973?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/FahedHermoza",
    "html_url": "https://github.com/FahedHermoza",
    "followers_url": "https://api.github.com/users/FahedHermoza/followers",
    "following_url": "https://api.github.com/users/FahedHermoza/following{/other_user}",
    "gists_url": "https://api.github.com/users/FahedHermoza/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/FahedHermoza/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/FahedHermoza/subscriptions",
    "organizations_url": "https://api.github.com/users/FahedHermoza/orgs",
    "repos_url": "https://api.github.com/users/FahedHermoza/repos",
    "events_url": "https://api.github.com/users/FahedHermoza/events{/privacy}",
    "received_events_url": "https://api.github.com/users/FahedHermoza/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "renosyah",
    "id": 22163616,
    "node_id": "MDQ6VXNlcjIyMTYzNjE2",
    "avatar_url": "https://avatars.githubusercontent.com/u/22163616?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/renosyah",
    "html_url": "https://github.com/renosyah",
    "followers_url": "https://api.github.com/users/renosyah/followers",
    "following_url": "https://api.github.com/users/renosyah/following{/other_user}",
    "gists_url": "https://api.github.com/users/renosyah/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/renosyah/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/renosyah/subscriptions",
    "organizations_url": "https://api.github.com/users/renosyah/orgs",
    "repos_url": "https://api.github.com/users/renosyah/repos",
    "events_url": "https://api.github.com/users/renosyah/events{/privacy}",
    "received_events_url": "https://api.github.com/users/renosyah/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "bagussatriaio",
    "id": 41253832,
    "node_id": "MDQ6VXNlcjQxMjUzODMy",
    "avatar_url": "https://avatars.githubusercontent.com/u/41253832?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/bagussatriaio",
    "html_url": "https://github.com/bagussatriaio",
    "followers_url": "https://api.github.com/users/bagussatriaio/followers",
    "following_url": "https://api.github.com/users/bagussatriaio/following{/other_user}",
    "gists_url": "https://api.github.com/users/bagussatriaio/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/bagussatriaio/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/bagussatriaio/subscriptions",
    "organizations_url": "https://api.github.com/users/bagussatriaio/orgs",
    "repos_url": "https://api.github.com/users/bagussatriaio/repos",
    "events_url": "https://api.github.com/users/bagussatriaio/events{/privacy}",
    "received_events_url": "https://api.github.com/users/bagussatriaio/received_events",
    "type": "User",
    "site_admin": false
  }
];

export default mockFollowers;